# specific branch build
trigger:
  branches:
    include:
    #- niqapps/*
    - master
    exclude:
    #- master
    - niqapps/*

pool:
  name: Default
  demands:
   - agent.name -equals NiQFlexAgent001 

stages:

- stage: WorkspaceOps #workspace is a directory used by agent
  jobs:
  - job: WorkspaceOpsWork
    workspace:
      clean: all  #outputs | resources | all # what to clean up before the job runs     
    steps:   
    - script: echo $(Build.ArtifactStagingDirectory)  #artifacts needed for the pipeline or upload artifacts
    - script: echo $(Build.SourcesDirectory) #application's source code dir
    - script: echo $(Build.BinariesDirectory) #where tasks write their outputs
    - script: echo $(Common.TestResultsDirectory) #where tasks upload their test results.

- stage: CICDOps
  jobs:
  - job: CICDOpsWork
    steps:   
    - script: echo This runs in the default shell on any machine
    #- bash: |
        #echo This multiline script always runs in Bash.
        #echo Even on Windows machines!  
      
