# specific branch build
trigger:
  branches:
    include:
    #- niqapps/*
    - master
    exclude:
    #- master
    - niqapps/*

pool:
  name: Default
  demands:
   - agent.name -equals NiQFlexAgent001 

stages:

- stage: WorkspaceOps #workspace is a directory used by agent
  jobs:
  - job: WorkspaceOpsWork
    workspace:
      clean: all  #outputs | resources | all # what to clean up before the job runs     
    steps:   
    - script: echo $(Build.ArtifactStagingDirectory)  #artifacts needed for the pipeline or upload artifacts
    - script: echo $(Build.SourcesDirectory) #application's source code dir
    - script: echo $(Build.BinariesDirectory) #where tasks write their outputs
    - script: echo $(Common.TestResultsDirectory) #where tasks upload their test results.

- stage: CICDOps
  jobs:
  - job: CICDOpsWork
    steps:   
    - task: CmdLine@2      
      inputs:
        workingDirectory: $(Build.SourcesDirectory) #Default to Build.SourcesDirectory if empty
        script: |
          echo Write your commands here          
          echo Hello world     
                 
- stage: CICDBuildArtifact
  jobs:
  - job: CICDBuildArtifactWork
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'       
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'clean cyclonedx:makeBom package'                

#https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-build-artifacts-v1?view=azure-pipelines&viewFallbackFrom=azure-devops
- stage: CICDPublishArtifact
  jobs:
  - job: CICDPublishArtifactWork
    steps:
    - task: CopyFiles@2
      inputs:
        contents: '_buildOutput/**'
        targetFolder: $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: MyBuildOutputs
        #TargetPath: \\NIQFLEX001\2023AzureDevOpsBuildArtifact 
        publishLocation: Container

- stage: ScriptTutorial
  jobs:
  - job: ScriptTutorialWork
    steps:
    - script: date /t
      displayName: Get the date
    - script: dir
      workingDirectory: $(Agent.BuildDirectory)
      displayName: List contents of a folder
    - script: |
        set MYVAR=foo
        set
      displayName: Set a variable and then display all
      env:
        aVarFromYaml: someValue  

