# specific branch build
trigger:
  branches:
    include:   
    - master
    exclude:   
    - niqapps/*
    - ado/*
    - tfado/*

pool:
  vmImage: 'windows-latest'

stages:

- stage: CI/CDStart
  jobs:
  - job: CI/CDSWork
    steps:   
    - task: CmdLine@2      
      inputs:
        workingDirectory: $(Build.SourcesDirectory) #Default to Build.SourcesDirectory if empty
        script: |          
          cd $(Build.SourcesDirectory)
          dir
          echo Write your commands here          
          echo Hello world     

- stage: WorkspaceOps #workspace is a directory used by agent
  jobs:
  - job: WorkspaceOpsWork
    workspace:
      clean: all  #outputs | resources | all # what to clean up before the job runs     
    steps:   
    - script: echo $(Build.ArtifactStagingDirectory)  #artifacts needed for the pipeline or upload artifacts
    - script: echo $(Build.SourcesDirectory) #application's source code dir
    - script: echo $(Build.BinariesDirectory) #where tasks write their outputs
    - script: echo $(Common.TestResultsDirectory) #where tasks upload their test results.
    
- stage: MicrosoftSecurityDevOps
  jobs:
  - job: MicrosoftSecurityDevOpsWork
    workspace:
      clean: all  #outputs | resources | all # what to clean up before the job runs     
    steps:   
    - task: MicrosoftSecurityDevOps@1
      displayName: 'Microsoft Security DevOps'
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
 

    

