# specific branch build
trigger:
  branches:
    include:
    #- niqapps/*
    - master
    exclude:
    #- master
    - niqapps/*

pool:
  name: Default
  demands:
   - agent.name -equals NiQFlexAgent001 

stages:

- stage: WorkspaceOps #workspace is a directory used by agent
  jobs:
  - job: WorkspaceOpsWork
    workspace:
      clean: all  #outputs | resources | all # what to clean up before the job runs     
    steps:   
    - script: echo $(Build.ArtifactStagingDirectory)  #artifacts needed for the pipeline or upload artifacts
    - script: echo $(Build.SourcesDirectory) #application's source code dir
    - script: echo $(Build.BinariesDirectory) #where tasks write their outputs
    - script: echo $(Common.TestResultsDirectory) #where tasks upload their test results.

- stage: CICDOps
  jobs:
  - job: CICDOpsWork
    steps:   
    - script: echo This runs in the default shell on any machine
    #- bash: |
        #echo This multiline script always runs in Bash.
        #echo Even on Windows machines!  
      
- stage: CIBuildArtifact
  jobs:
  - job: CIBuildArtifactWork
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'       
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'clean cyclonedx:makeBom package'                

- stage: CIPublishArtifact
  jobs:
  - job: CIPublishArtifactWork
    steps:
    - task: CopyFiles@2
      inputs:
        contents: '_buildOutput/**'
        targetFolder: $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: MyBuildOutputs
        TargetPath: \\NIQFLEX001\2023AzureDevOpsBuildArtifact 
        publishLocation: FilePath #Default value: Container
      