server:
  port: 9898

---
spring:
  application:
    name: authserver
info:
  app:
    name: ${spring.application.name}
---
spring:
  security:
    oauth2:
      client:
        registration:
          google-idp:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID:google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:google-client-secret}
            scope: openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
            client-name: Sign in with Google
          github-idp:
            provider: github
            client-id: ${GITHUB_CLIENT_ID:github-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:github-client-secret}
            scope: user:email, read:user
            client-name: Sign in with GitHub
        provider:
          google:
            user-name-attribute: email
          github:
            user-name-attribute: login

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

---
#Expose everything over HTTP except the env and beans endpoints
#management.endpoints.web.exposure.include: "*"
#management.endpoints.web.exposure.exclude: env,beans
management.endpoints.web.exposure.include: "*"
management.metrics.tags.application: ${spring.application.name}
---
logging.file.name: authserver.log
logging.level.org.springframework: INFO
