spring:
  datasource:
    url: jdbc:h2:file:~/OAuth2DB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE #jdbc:h2:mem:mydb or jdbc:h2:file:/data/demo
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    open-in-view: true
    show-sql: true
    properties:
      hibernate.jdbc.batch_size: 20
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_structured_entries: false
      hibernate.cache.use_minimal_puts: false
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    jpa:
      repositories:
        bootstrap-mode: default
        enabled: true